### ISSUE TITLE
Backpropagation

### ISSUE THREAD

**Issue by ikostrikov** [eladhoffer/recurrent.torch#2]
Backpropagation doesn't work for me. It tries to index a module for timeframe n + 1 which does not exist:

Recurrent.lua:263: attempt to index a nil value

**Comment by eladhoffer** [comment]
Share (or send me) your code and I'll take a look

**Comment by ikostrikov** [comment]
Here it is:
https://gist.github.com/ikostrikov/31812a244c0e6c9ea269

Work in progress so it might not work in overall. But at the moment it breaks at line 112.

**Comment by ikostrikov** [comment]
I think that the problem is in the single timeframe mode. It works perfectly in the sequential mode.

**Comment by eladhoffer** [comment]
You're right, there's a bug in single mode. I'll try to fix it by tomorrow

**Comment by eladhoffer** [comment]
fixed
